### ISSUE TITLE
New blog: Stats and R

### ISSUE THREAD

**Issue by AntoineSoetewey** [rushter/data-science-blogs#100]
Hi,

Would it be possible to add the following blog?
Stats and R: https://www.statsandr.com/

It is a blot about statistics and its applications in R.

Feel free to contact me if you need additional information.

Best,
Antoine

**Comment by rushter** [comment]
Hi, I've added your blog. https://github.com/rushter/data-science-blogs/commit/9121d728fdebd677e5d6b365e62d73d02619e80c

**Comment by AntoineSoetewey** [comment]
Thanks!
