### ISSUE TITLE
UW Data Science Blog

### ISSUE THREAD

**Issue by jaytaylopub** [rushter/data-science-blogs#38]
I wanted to propose adding the blog for University of Wisconsin Data Science Degree Program to this hub. It's up to date, and very informative.

**Comment by rushter** [comment]
Can i have a link?

**Comment by jaytaylopub** [comment]
@rushter  http://datasciencedegree.wisconsin.edu/blog/

**Comment by jaytaylopub** [comment]
Thoughts?

**Comment by rushter** [comment]
https://github.com/rushter/data-science-blogs/commit/15963339979674d9ec34ca61cab4e40626e544f3
