### ISSUE TITLE
Feed tracker for README.md

### ISSUE THREAD

**Issue by rasbt** [rushter/data-science-blogs#5]
I was just thinking that it could be worthwhile to embed a widget that shows the 10 latests posts from all the blogs from this list (with automatic updates of course) at the top or bottom of this page. E.g., for people who don't have an RSS reader installed; or just in general to make this page even more appealing. What do you think?

**Comment by rushter** [comment]
My first idea was to create a blog aggregator (website). But first, i decided to check people's interest on GitHub.
I don't think GitHub can handle aggregation in a good way.

**Comment by rasbt** [comment]
Sure, I guess I would wait a little since there are a lot of good new suggestions coming in. In general you could use GitHub pages to set up something like that https://pages.github.com

**Comment by rushter** [comment]
I just created an aggregator based on this list. 
Do you have any ideas about how to improve it?
http://dsguide.biz/reader/

**Comment by elmerehbi** [comment]
Nice work with the aggregator.
How was it accomplished?

**Comment by rasbt** [comment]
Wow, that's really cool! Nice work! 

Only one little note: Currently, the "DsGuide" button link in the top left corner doesn't work (I assume that it should link to http : // dsguide . biz ?)

Btw how often does it fetch updates and is the tagging/categorization also automated?

**Comment by rushter** [comment]
The "DsGuide" button is placed instead of logo :)
It updates every 30 minutes, all automatically.

My next idea is to collect videos about data science by using YouTube API.

**Comment by rasbt** [comment]
> The "DsGuide" button is placed instead of logo :)

I see, but shouldn't it link back to the starting page when you click it? Right now, it's only appending an `#` parameter to the address

**Comment by rushter** [comment]
Fixed :).
